name: Build iOS Library

on: 
  push:
    branches:
      - feature/add-ios-library

env:
  PROJECT_NAME: AppAmbit
  SCHEME: AppAmbit
  APP_XCFRAMEWORK: AppAmbit.xcframework
  XCODE-VERSION: 16.2
  FOLDER_PATH: build
  
jobs:
  ios-library:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean up build directory
        run: |
          rm -rf ${{ env.FOLDER_PATH }}
          rm -rf ${{ env.APP_XCFRAMEWORK }}

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE-VERSION }}

      - name: Build Library for iOS
        run: |
          xcodebuild archive \            
          -scheme $SCHEME \
          -destination 'generic/platform=iOS' \          
          -archivePath ./$FOLDER_PATH/ios_devices.xcarchive \  
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES

      - name: Build Library for iOS Simulator
        run: |
          xcodebuild archive \            
          -scheme $SCHEME \
          -destination 'generic/platform=iOS Simulator' \
          -archivePath ./$FOLDER_PATH/ios_simulator.xcarchive \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES

      - name: Create XCFramework
        run: |
          xcodebuild -create-xcframework \
          -framework ./$FOLDER_PATH/ios_devices.xcarchive/Products/Library/Frameworks/AppAmbit.framework \
          -framework ./$FOLDER_PATH/ios_simulator.xcarchive/Products/Library/Frameworks/AppAmbit.framework \
          -output ./$APP_XCFRAMEWORK

      - name: Packing XCFramework
        run: |
          zip -r $APP_XCFRAMEWORK.zip $APP_XCFRAMEWORK

      - name: Upload XCFramework as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_XCFRAMEWORK }}.zip
          path: ${{ env.APP_XCFRAMEWORK }}.zip